nKanban/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace nKanban.Models
{
    public class RegisterViewModel
    {
        [Required(ErrorMessage = "First name is required.")]
        [Display(Name = "First Name")]
        [StringLength(50, ErrorMessage = "First name cannot be more than 50 characters.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required.")]
        [Display(Name = "Last Name")]
        [StringLength(50, ErrorMessage = "Last name cannot be more than 50 characters.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Email is required.")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [StringLength(100, ErrorMessage = "Email cannot be more than 100 characters.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Password must be at least 6 characters and no more than 20 characters.")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Password confirmation is required.")]
        [Display(Name = "Password Confirmation")]
        [DataType(DataType.Password)]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Password confirmation must be at least 6 characters and no more than 20 characters.")]
        [Compare("Password", ErrorMessage = "Password confirmation must match Password.")]
        public string PasswordConfirmation { get; set; }

        [Display(Name = "Organization")]
        [StringLength(100, ErrorMessage = "Organization name cannot be more than 100 characters.")]
        public string OrganizationName { get; set; }

        [Display(Name = "Address One")]
        [StringLength(255, ErrorMessage = "Address one cannot be more than 255 characters.")]
        public string Address1 { get; set; }

        [Display(Name = "Address Two")]
        [StringLength(255, ErrorMessage = "Address two cannot be more than 255 characters.")]
        public string Address2 { get; set; }

        [Display(Name = "City")]
        [StringLength(100, ErrorMessage = "City cannot be more than 100 characters.")]
        public string City { get; set; }

        [Display(Name = "Province/State")]
        public Guid? ProvinceId { get; set; }

        [Display(Name = "Country")]
        public Guid? CountryId { get; set; }

        [Display(Name = "Postal/Zip Code")]
        [StringLength(20, ErrorMessage = "Postal/Zip code cannot be more than 20 characters.")]
        public string PostalCode { get; set; }

        //properties used for New
        public IEnumerable<SelectListItem> Countries { get; set; }
        public IEnumerable<SelectListItem> Provinces { get; set; }

        public RegisterViewModel()
        {
            Countries = Enumerable.Empty<SelectListItem>();
            Provinces = Enumerable.Empty<SelectListItem>();
        }
    }
}

nKanban/Controllers/LookupController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using nKanban.Services;
using nKanban.Domain;
using System.Web.SessionState;

namespace nKanban.Controllers
{
    [SessionState(SessionStateBehavior.Disabled)]
    public class LookupController : AbstractBaseController
    {
        private readonly ISimpleService _lookupService;

        public LookupController(ISimpleService lookupService)
        {
            if (lookupService == null)
            {
                throw new ArgumentNullException("lookupService");
            }

            _lookupService = lookupService;
        }

        [HttpGet]
        public ActionResult Provinces(Guid id)
        {
            var provinces = _lookupService.GetAll<Province>(p => p.CountryId == id).OrderBy(p => p.Name).ToList();
            return Json(provinces, JsonRequestBehavior.AllowGet);
        }
    }
}

nKanban/Controllers/RegisterController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using nKanban.Models;
using nKanban.Services;
using nKanban.Domain;
using AutoMapper;
using nKanban.Filters;

namespace nKanban.Controllers
{
    [AnonymousOnlyFilter]
    public class RegisterController : AbstractBaseController
    {
        private readonly IUserService _userService;
        private readonly ILoginService _loginService;
        private readonly ISimpleService _lookupService;

        public RegisterController(IUserService userService, ILoginService loginService, ISimpleService lookupService)
        {
            if (userService == null)
            {
                throw new ArgumentNullException("userService");
            }

            if (loginService == null)
            {
                throw new ArgumentNullException("loginService");
            }

            if (lookupService == null)
            {
                throw new ArgumentNullException("lookupService");
            }

            _lookupService = lookupService;
            _loginService = loginService;
            _userService = userService;
        }

        public ActionResult New()
        {
            var model = new RegisterViewModel();
            PopulateRegisterModel(model);

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = Mapper.Map<User>(model);
                var organization = Mapper.Map<Organization>(model);

                if (model.CountryId.HasValue)
                {
                    organization.Country = _lookupService.Get<Country>(model.CountryId.Value);
                }

                if (model.ProvinceId.HasValue)
                {
                    organization.Province = _lookupService.Get<Province>(model.ProvinceId.Value);
                }

                var errors = _userService.CreateUser(user, model.Password, organization);

                if (!errors.Any())
                {
                    _loginService.LoginUser(user, false);
                    SetRedirectMessage(MessageType.Success, "Successfully created your account.");
                    return RedirectToRoute("Dashboard");
                }
                else
                {
                    AddServiceErrors(errors);
                }
            }

            PopulateRegisterModel(model);
            return View("New", model);
        }

        private void PopulateRegisterModel(RegisterViewModel model)
        {
            var countries = _lookupService.GetAll<Country>().
                OrderBy(c => c.Name).Select(c => new SelectListItem()
                                                {
                                                    Text = c.Name,
                                                    Value = c.Id.ToString(),
                                                    Selected = model.CountryId.HasValue && model.CountryId.Value == c.Id
                                                }).ToList();
            model.Countries = countries;

            if (model.CountryId.HasValue)
            {
                var provinces = _lookupService.GetAll<Province>(p => p.CountryId == model.CountryId.Value).
                    OrderBy(p => p.Name).Select(p => new SelectListItem() 
                                                    { 
                                                        Selected = model.ProvinceId.HasValue && model.ProvinceId.Value == p.Id,
                                                        Text = p.Name,
                                                        Value = p.Id.ToString()
                                                    }).ToList();

                model.Provinces = provinces;
            }
        }
    }
}

nKanban/Views/Register/New.cshtml
@model nKanban.Models.RegisterViewModel
@{
    ViewBag.Title = "nKanban :: Register";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<h2>
    Register for nKanban</h2>
@using (Html.BeginForm("Create", "Register", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary("There were some errors ...", new { id = "validation-errors" })

    <fieldset>
        <legend>Please fill in the required information below</legend>
        <div class="control-group">
            @Html.LabelFor(m => m.FirstName, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.FirstName, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.FirstName, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.LastName, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.LastName, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.LastName, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.Email, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.Email, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.Email, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.Password, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.Password, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.Password, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.PasswordConfirmation, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.PasswordConfirmation, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.PasswordConfirmation, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
    </fieldset>
    
    <fieldset>
        <legend>Organizational Information</legend>
        <div class="control-group">
            @Html.LabelFor(m => m.OrganizationName, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.OrganizationName, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.OrganizationName, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.Address1, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.Address1, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.Address1, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.Address2, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.Address2, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.Address2, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.City, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.City, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.City, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.ProvinceId, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(m => m.ProvinceId, Model.Provinces, String.Empty, new { @class = "input-medium" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.CountryId, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(m => m.CountryId, Model.Countries, String.Empty, new { @class = "input-medium" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.PostalCode, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.PostalCode, new { @class = "input-small" })
                @Html.ValidationMessageFor(m => m.PostalCode, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Register" />
        </div>
    </fieldset>
}
@Html.Hidden("ProvinceLookupUrl", Url.Action("Provinces", "Lookup"))
<script type="text/javascript" src="@Url.Content("~/Scripts/Register/new.js")"></script>