nKanban/Controllers/SessionController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using nKanban.Models;
using nKanban.Services;
using nKanban.Filters;

namespace nKanban.Controllers
{
    public class SessionController : AbstractBaseController
    {
        private readonly IUserService _userService;
        private readonly ILoginService _loginService;

        public SessionController(IUserService userService, ILoginService loginService)
        {
            if (userService == null)
            {
                throw new ArgumentNullException("userService");
            }

            if (loginService == null)
            {
                throw new ArgumentNullException("loginService");
            }

            _loginService = loginService;
            _userService = userService;
        }

        [AnonymousOnlyFilter]
        public ActionResult New()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        [AnonymousOnlyFilter]
        public ActionResult Create(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var errors = _userService.VerifyLogin(model.UserName, model.Password);

                if (!errors.Any())
                {
                    var user = _userService.GetUser(model.UserName);
                    _loginService.LoginUser(user, model.RememberMe);
                    return RedirectToRoute("Dashboard");
                }
            }

            return View("New", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Delete()
        {
            _loginService.Logoff();
            SetRedirectMessage(MessageType.Success, "Successfully logged you out of the application.");
            return RedirectToAction("Index", "Home");
        }
    }
}

nKanban/Views/Session/New.cshtml
@model nKanban.Models.LoginViewModel

@{
    ViewBag.Title = "nKanban :: Login";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>
    Login to nKanban</h2>
@using (Html.BeginForm("Create", "Session", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary("There were some errors ...", new { id = "validation-errors" })
    
    <fieldset>
        <div class="control-group">
            @Html.LabelFor(m => m.UserName, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.UserName, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.UserName, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.Password, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.Password, new { @class = "input-xlarge" })
                @Html.ValidationMessageFor(m => m.Password, "!", new { @class = "help-inline field-error" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.RememberMe, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.RememberMe, new { @class = "input-xlarge" })
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="btn btn-primary" id="Login" value="Login" />
        </div>
    </fieldset>
}