nKanban/Models/DashboardViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace nKanban.Models
{
    public class DashboardViewModel
    {
        public IEnumerable<KanbanBoardViewModel> KanbanBoards { get; set; }

        public DashboardViewModel()
        {
            KanbanBoards = Enumerable.Empty<KanbanBoardViewModel>();
        }
    }
}

nKanban/Models/KanbanBoardViewModel.cs
using System;

namespace nKanban.Models
{
    public class KanbanBoardViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
}

nKanban/Controllers/DashboardController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using nKanban.Models;
using nKanban.Services;

namespace nKanban.Controllers
{
    [Authorize]
    public class DashboardController : AbstractBaseController
    {
        private readonly IUserService _userService;
        private readonly IKanbanBoardService _kanbanBoardService;

        public DashboardController(IUserService userService, IKanbanBoardService kanbanBoardService)
        {
            if (userService == null)
            {
                throw new ArgumentNullException("userService");
            }

            if (kanbanBoardService == null)
            {
                throw new ArgumentNullException("kanbanBoardService");
            }

            _userService = userService;
            _kanbanBoardService = kanbanBoardService;
        }

        public ActionResult Show()
        {
            var kanbanBoards = _kanbanBoardService.GetKanbanBoardsByUser(CurrentUser.Id);
            var models = kanbanBoards.Select(Mapper.Map<KanbanBoardViewModel>);

            var model = new DashboardViewModel() { KanbanBoards = models };

            return View(model);
        }
    }
}

nKanban/Controllers/KanbanBoardController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using nKanban.Domain;
using nKanban.Models;
using nKanban.Services;

namespace nKanban.Controllers
{
    [Authorize]
    public class KanbanBoardController : AbstractBaseController
    {
        private readonly IKanbanBoardService _kanbanBoardService;

        public KanbanBoardController(IKanbanBoardService kanbanBoardService)
        {
            if(kanbanBoardService == null)
            {
                throw new ArgumentNullException("kanbanBoardService");
            }

            _kanbanBoardService = kanbanBoardService;
        }

        public ActionResult New()
        {
            var model = new CreateKanbanBoardViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CreateKanbanBoardViewModel model)
        {
            if(ModelState.IsValid)
            {
                var board = Mapper.Map<KanbanBoard>(model);
                var errors = _kanbanBoardService.CreateKanbanBoard(CurrentUser.Id, board);

                if(!errors.Any())
                {
                    return RedirectToRoute("Dashboard");
                }

                AddServiceErrors(errors);
            }

            return View("New", model);
        }
    }
}

nKanban/Views/Dashboard/Show.cshtml
@model nKanban.Models.DashboardViewModel
@{
    ViewBag.Title = "nKanban :: Dashboard";
    Layout = "~/Views/Shared/_LoggedInLayout.cshtml";
}
<h2>
    Welome to your dashboard</h2>
<div>
    <h3>
        Your Kanban boards:</h3>
    @if(Model.KanbanBoards.Any())
    {
        foreach(var board in Model.KanbanBoards)
        {
            Html.RenderPartial("_KanbanBoard", board);
        }
    }
    else
    {
            Html.RenderPartial("_NoKanbanBoards");
    }
</div>

nKanban/Views/Dashboard/_KanbanBoard.cshtml
@model nKanban.Models.KanbanBoardViewModel

<div class="kanban-board">
    @Html.HiddenFor(m => m.Id)
    @Model.Name
</div>

nKanban/Views/Dashboard/_NoKanbanBoards.cshtml
<div>
    You have not yet created any Kanban boards.
    @Html.ActionLink("Create One", "New", "KanbanBoard", null, new { @class = "btn btn-primary"})
</div>